### ISSUE TITLE
🐛 [BUG] - `generic_fss_sim` fails to connect to 42 (`fortytwo`) – DNS resolution error blocks FSS telemetry

### ISSUE THREAD

**Issue by nerbivol** [nasa/nos3#763]
### Description

**Description**:

While following the standard NOS3 instructions (from README) to build and run the stack (`make prep`, `make`, `make launch`), I encountered a failure in the `generic_fss_sim` component. The logs show that the simulator attempts to connect to a host named `fortytwo` at port `4284`, but fails due to DNS resolution issues.

This seems consistent with [#602](https://github.com/nasa/nos3/issues/602)

---

**Steps to Reproduce**:

1. Clone NOS3 from GitHub
2. Navigate to the repo:

   ```bash
   cd ~/Desktop/github-nos3  
   ```
3. Run build and launch:

   ```bash
   make prep  
   make  
   make launch  
   ```
4. Observe that 42 windows **do not** appear.

<img width="1280" height="843" alt="Image" src="https://github.com/user-attachments/assets/2f53fdd3-567e-4a28-b747-a157c27cb3e1" />

6. Check logs for `generic_fss_sim` – key failure output:
```
[ ERROR ] - SimData42SocketProvider::connect_as_42_socket_client:  Error getting address for host fortytwo, port 4284: Temporary failure in name resolution  
[ ERROR ] - SimData42SocketProvider::connect_reader_thread_as_42_socket_client:  Unable to connect TELEMETRY host fortytwo, port 4284 to 42, no thread will be started to listen :-(
```

---

**Full FFS output**:
```
2025-07-15 20:29:35.064141 [ DEBUG ] - SimConfig::SimConfig:  sim_logger is NOW valid.
2025-07-15 20:29:35.069078 [ INFO  ] - main:  "generic_fss_sim" simulator starting
2025-07-15 20:29:35.072238 [ DEBUG ] - SimConfig::run_simulator:  SimConfig is created, logger is valid, and run_simulator is starting.
2025-07-15 20:29:35.075547 [ INFO  ] - SimConfig::get_config_for_simulator:  Loading plug-in library libgeneric_fss_sim.so
2025-07-15 20:29:35.463063 [ INFO  ] - SimHardwareModelFactory::RegisterMaker:  Registered hardware model for key GENERIC_FSS
2025-07-15 20:29:35.491468 [ INFO  ] - SimDataProviderFactory::RegisterMaker:  Registered data provider for key GENERIC_FSS_42_PROVIDER
2025-07-15 20:29:35.491648 [ DEBUG ] - SimConfig::get_config_for_simulator:  Configuration for simulator "generic_fss_sim" is:

2025-07-15 20:29:35.492584 [ DEBUG ] - 
<?xml version="1.0" encoding="utf-8"?>
<common>
    <log-config-file>sim_log_config.xml</log-config-file>
    <!-- https://nsidc.org/data/icesat/glas-date-conversion-tool/date_convert/​ -->
    <!-- 533156400.0 UTC = 11/23/2016 07:00:00.00 UTC -->
    <!-- 552110400.0 UTC = 06/30/2017 16:00:00.00 UTC -->
    <!-- 814048200.0 UTC = 10/18/2025 08:30:00.00 UTC -->
    <absolute-start-time>814048200.0</absolute-start-time>
    <sim-microseconds-per-tick>10000</sim-microseconds-per-tick>
    <real-microseconds-per-tick>10000</real-microseconds-per-tick>
    <nos-connection-string>tcp://nos_engine_server:12001</nos-connection-string>
</common>
<simulator>
    <name>generic_fss_sim</name>
    <active>true</active>
    <library>libgeneric_fss_sim.so</library>
    <hardware-model>
        <type>GENERIC_FSS</type>
        <connections>
            <connection>
                <type>command</type>
                <bus-name>command</bus-name>
                <node-name>fss-command</node-name>
            </connection>
            <connection>
                <type>spi</type>
                <bus-name>spi_1</bus-name>
                <chip-select>1</chip-select>
            </connection>
        </connections>
        <data-provider>
            <type>GENERIC_FSS_42_PROVIDER</type>
            <hostname>fortytwo</hostname>
            <port>4284</port>
            <max-connection-attempts>30</max-connection-attempts>
            <retry-wait-seconds>1</retry-wait-seconds>
            <spacecraft>0</spacecraft>
        </data-provider>
    </hardware-model>
</simulator>

2025-07-15 20:29:35.502834 [ INFO  ] - SimHardwareModelFactory::Create:  Creating hardware model for key GENERIC_FSS
2025-07-15 20:29:35.758072 [ DEBUG ] - SimIHardwareModel::SimIHardwareModel:  Command node fss-command now active on command bus command.
2025-07-15 20:29:35.759096 [ INFO  ] - Generic_fssHardwareModel::Generic_fssHardwareModel:  NOS Engine connection string: tcp://nos_engine_server:12001.
2025-07-15 20:29:35.761736 [ INFO  ] - SimDataProviderFactory::Create:  Creating data provider for key GENERIC_FSS_42_PROVIDER
2025-07-15 20:29:35.763185 [ DEBUG ] - SimData42SocketProvider::SimData42SocketProvider:  No COMMAND port (0) to 42 requested, none connected.
2025-07-15 20:29:35.837482 [ ERROR ] - SimData42SocketProvider::connect_as_42_socket_client:  Error getting address for host fortytwo, port 4284: Temporary failure in name resolution
2025-07-15 20:29:35.841090 [ ERROR ] - SimData42SocketProvider::connect_reader_thread_as_42_socket_client:  Unable to connect TELEMETRY host fortytwo, port 4284 to 42, no thread will be started to listen :-(
2025-07-15 20:29:35.841900 [ INFO  ] - Generic_fssHardwareModel::Generic_fssHardwareModel:  Data provider GENERIC_FSS_42_PROVIDER created.
2025-07-15 20:29:36.099266 [ INFO  ] - Generic_fssHardwareModel::Generic_fssHardwareModel:  Now on time bus named command.
2025-07-15 20:29:36.637341 [ INFO  ] - Generic_fssHardwareModel::Generic_fssHardwareModel:  Now on SPI bus name spi_1, chip select 1.
2025-07-15 20:29:36.642209 [ INFO  ] - Generic_fssHardwareModel::Generic_fssHardwareModel:  Construction complete.

```

### Reproduction steps

```bash
1. Clone NOS3 from GitHub
2. Navigate to the repo:

   
   cd ~/Desktop/github-nos3  
   
3. Run build and launch:

   
   make prep  
   make  
   make launch  
   
4. Observe that 42 windows **do not** appear.
```

### Screenshots

```bash

```

### Logs

```bash

```

### OS

Linux (Direct Clone)

**Comment by zlynch2** [comment]
Hi @nerbivol 
We are currently working through our 1.7.3 release. We had to update our 42 recently which may be causing issues. I apologize for the inconvenience. We are trying to have 1.7.3 released by the end of the week. this should resolve your 42 problems, thanks!

**Comment by nerbivol** [comment]
Thank you. I will wait for further updates.

**Comment by zlynch2** [comment]
@nerbivol we have just released 1.7.3. feel free to pull nos3 like you have and update hopefully this fixes your issue, and I apologize for the inconvenience!

**Comment by PinakSharmaa** [comment]
Hello @nerbivol ,

Were you able to resolve this issue? I am also experiencing this issue with the sc01-fortytwo container starting and shutting down immediately.

**Comment by zlynch2** [comment]
@PinakSharmaa 

Yes, please clone nos3 again or update to release 1.7.3. This changed our 42 configuration slightly which accidentally affected previous versions of NOS3. I apologize for the inconvenience.

**Comment by PinakSharmaa** [comment]
Hi @zlynch2 

Thank you for your reply. Apologies for not providing more information earlier. I have actually cloned the most recent version of 'main' (Release 1.7.3 - Commit: [6c5f135](https://github.com/nasa/nos3/commit/6c5f1357a90b16e36e3c9e971a65e103e662e5db)), but I am still having issues with the 42 dynamics and COSMOS container as well. I have re-cloned it and followed the steps on the installation page:

1. `git clone https://github.com/nasa/nos3.git`
2. `cd nos3`
3. `git submodule update --init --recursive`
4. Make virtual environment: `python3 -m venv .venv` and then `source .venv/bin/activate`
4. `make prep`
5. `make`
6. `make launch`

Now when I run `make launch` or run launch using the gui from `make igniter`, I notice the 42 terminal window open for a second and then disappear, which also causes the "42 truth sim" terminal to also crash seconds later. Ultimately I am left only with these following terminals/containers running:

<img width="1129" height="797" alt="Image" src="https://github.com/user-attachments/assets/7cfc2848-5a09-41b0-a67b-709417f460a8" />

No 42 GUI windows open, nor does COSMOS for reasons unknown to me. I have tried a few things to fix this on my end. 

1. I investigated if there was any issue with the 42 dynamics library and any installation issues on my end. I cloned the 42 repo (https://github.com/ericstoneking/42, and tried to compile it and it did not work. I got a message saying: `fatal error: GL/glut.h: No such file or directory`. This led me to install freeglut3-dev and doing so allowed me to compile and run the 42 Demo.  I tried to `make launch` again in nos3 and 42 still would not stay on. 

2. I investigated what the 42 window was printing before crashing. I changed a line in the `cfg/build/launch.sh` file. I commented out line 98:
```
gnome-terminal --tab --title=$SC_NUM" - 42" -- $DFLAGS -e DISPLAY=$DISPLAY -v $USER_NOS3_DIR:$USER_NOS3_DIR -v /tmp/.X11-unix:/tmp/.X11-unix:ro --name $SC_NUM"-fortytwo" -h fortytwo --network=$SC_NETNAME -w $USER_NOS3_DIR/42 -t $DBOX $USER_NOS3_DIR/42/42 NOS3InOut
```
and replaced it with:
```
$DFLAGS -e DISPLAY=$DISPLAY -v $USER_NOS3_DIR:$USER_NOS3_DIR -v /tmp/.X11-unix:/tmp/.X11-unix:ro --name $SC_NUM"-fortytwo" -h fortytwo --network=$SC_NETNAME -w $USER_NOS3_DIR/42 $DBOX $USER_NOS3_DIR/42/42 NOS3InOut
```
forcing 42 to  run in the main terminal. The terminal then printed out the following:

```
/cfg/build/launch.sh
Make data folders...
Create ground networks...
b5654a25aeb4f389e3d08ead2cab659b0a93b211bf8dc673bb10b9e6f70b5bbd

Launch GSW...

COSMOS launch...
Create NOS interfaces...

sc01  - Create spacecraft network...
416789eaf5e2e9a20c0c6ad74621a7dd483911229d171d96a95f74fe190adbac

sc01  - Connect GSW  cosmos-openc3-operator-1  to spacecraft network...
Error response from daemon: No such container: cosmos-openc3-operator-1

sc01  - 42...
non-network local connections being added to access control list

docker: Error response from daemon: mounts denied: 
The path /tmp/.X11-unix is not shared from the host and is not known to Docker.

You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/ for more info.

Run 'docker run --help' for more information

sc01  - OnAIR...
sc01  - Flight Software...
sc01  - Simulators...
sc01  - CryptoLib...
NOS Time Driver...

Docker launch script completed!
```

As seen from above the the directory `/tmp/.X11-unix` was not on the allowed list for docker, so I fixed that. After saving the docker settings I tried to `make launch` again (after reverting back the `cfg/build/launch.sh` file) and the 42 simulator does now print something else... but the GUI still doesn't load. It simply prints something like the following before crashing again..:

```
sc01  - 42...
non-network local connections being added to access control list

Material material_1 is not in Matl structure
Setting material to default
Material material_1 is not in Matl structure
Setting material to default
Material material_1 is not in Matl structure
Setting material to default
Material material_1 is not in Matl structure
Setting material to default
Material material_1 is not in Matl structure
Setting material to default

...

Material material_3 is not in Matl structure
Setting material to default
Material material_4 is not in Matl structure
Setting material to default
Material material_3 is not in Matl structure
Setting material to default
Reached CmdScript EOF at Time = 0.000000
Server is listening on port 4278
```

3. Regarding the cosmos container issue, I tried to fix the issue by deleting local images and volumes and re-running the installation steps. When I did so I see this output when I run the `make` step:
```
Prepare openc3-cosmos containers...

WARN[0000] /home/pinak/.nos3/cosmos/compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 

[+] Running 70/74

 ✔ openc3-redis Pulled  59.7s 
 ✔ openc3-redis-ephemeral Pulled  59.7s 
 ✔ openc3-minio Pulled  63.1s 
 ✔ openc3-operator Pulled  82.4s 
 ✔ openc3-traefik Pulled   59.6s 
 ✔ openc3-cosmos-script-runner-api Pulled   83.2s 
 ✔ openc3-cosmos-init Pulled  83.6s 
 ✔ openc3-cosmos-cmd-tlm-api Pulled  83.3s                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                [+] Running 13/13

 ✔ Network openc3-cosmos-network                       Created   0.1s 
 ✔ Volume cosmos_openc3-redis-ephemeral-v              Created   0.0s 
 ✔ Volume cosmos_openc3-gems-v                         Created   0.0s 
 ✔ Volume cosmos_openc3-redis-v                        Created   0.0s 
 ✔ Volume cosmos_openc3-minio-v                        Created  0.0s 
 ✔ Container cosmos-openc3-redis-1                     Started    2.3s 
 ✔ Container cosmos-openc3-minio-1                     Started   2.4s 
 ✔ Container cosmos-openc3-redis-ephemeral-1           Started  2.4s 
 ✔ Container cosmos-openc3-traefik-1                   Started   3.7s 
 ✔ Container cosmos-openc3-cosmos-script-runner-api-1  Started 3.1s 
 ✔ Container cosmos-openc3-cosmos-cmd-tlm-api-1        Started  3.4s 
 ✔ Container cosmos-openc3-operator-1                  Started  3.4s 
 ✔ Container cosmos-openc3-cosmos-init-1               Started  4.3s 


Plugin openc3-cosmos-nos3 successfully generated!
cp: cannot stat '../../lib': No such file or directory

Create plugin...

Build plugin...
gem build openc3-cosmos-nos3
openc3cli validate openc3-cosmos-nos3-1.0.202510241446.gem
  Successfully built RubyGem
  Name: openc3-cosmos-nos3
  Version: 1.0.202510241446
  File: openc3-cosmos-nos3-1.0.202510241446.gem
Installing openc3-cosmos-nos3-1.0.202510241446.gem
Successfully validated openc3-cosmos-nos3-1.0.202510241446.gem
```

Could the `cp: cannot stat '../../lib': No such file or directory` line be indicative of an issue for me?  

For your reference here are the images, containers and volumes that run:

Images:

<img width="1317" height="583" alt="Image" src="https://github.com/user-attachments/assets/e8500a45-ad38-432b-97e1-4d1cad778f3a" />

Containers:

<img width="1331" height="1059" alt="Image" src="https://github.com/user-attachments/assets/6695d055-9b4c-40fc-8474-1a22ec0e4c6e" />

Volumes:

<img width="1317" height="377" alt="Image" src="https://github.com/user-attachments/assets/74820607-a651-42b4-8e1a-b05f15ec7afe" />


For your reference I am running this on a Linux machine (without VM):

OS Version: Kubuntu 24.04
Hardware: 16 × AMD Ryzen 7 Pro 7735U with Radeon Graphics


Would appreciate any assistance on this issue. Let me know if you require more information. Thank you!

**Comment by zlynch2** [comment]
@PinakSharmaa 
First off excellent Debugging, your description of whats happening is very helpful.

This sounds like an X11 forwarding issue on your host. If there is a way to change your preferences to keep the terminal open after exiting, you may see a cosmos terminal and a 42 terminal display an X11 error, or cannot connect to X server :0. Also it is important to not for release 1.7.3 we are running docker version 26.1.3 and we are on ubuntu 22.04. 

First lets verify if your 42 and cosmos terminals are launching but terminating by keeping them open and verifying the error messages. Also please verify your other containers are not failing. 42 in nos3 is dependent on the hardware sims to subscribe to 42. If one of those containers fail, 42 wont launch. 

Thanks!

**Comment by PinakSharmaa** [comment]
Hi @zlynch2 

Thank you for your helpful reply. I edited the launch.sh script to keep the sc01-fortytwo terminal open instead of closing and we can see that you are right, I does look like its an X11 forwarding issue:

```
...
...
Server side of socket established.
Server is listening on port 4283
Server side of socket established.
Initializing GLUT
freeglut (/home/pinak/.nos3/42/42): failed to open display ':0'
```
It appears that my attempt to simply add the `/tmp/` folder of my machine to the docker virtual file shares (in docker desktop) does not solve the issue. Is my docker and ubuntu version a critical requirement to make nos3 run? I am on Kubuntu 24.04 and Docker version 28.5.1. 

I have tried to run the `xhost +` command which returns `access control disabled, clients can connect from any host`, as intended for our debugging purpose. Even after doing that It still doesn't work. Could using docker-desktop be a culprit here?  From my understanding Docker Desktop for Linux doesn't run containers directly on the host host. It runs them inside a lightweight virtual machine.

Would appreciate any thoughts and advice on how to proceed. 

As I am writing this I have also been trying to go with the VM path with vagrant on my other personal windows machine and that seemed to have worked on this attempt of running `make`. The VM can run all of the containers but I am concerned this is not a deterministic result and I just got lucky this time. Even this time I saw a message like:
```
make[2]: warning: Clock skew detected. Your build may be incomplete
```
Is that expected when using the VM in VirtualBox? Thank you so much for your replies and assistance. Please let me know if you require more information.

**Comment by zlynch2** [comment]
HI @PinakSharmaa 
Locally If I was having trouble with x11 issues I remember installing some dependencies manually. 

sudo apt-get install docker
sudo apt-get install docker.io
sudo usermod -aG docker $USER (restart after)
xhost +
sudo systemctl restart ssh

Possiblly these as well:
sudo apt install --reinstall libxcb-xinerama0
sudo apt install libqt5x11extras5
sudo apt install libxcb-cursor0

(fresh resatart doesnt hurt after as well). Note installing docker manually on a ubuntu linux 22.04 host machine. This helped with the x11 forwarding issues, becasue I was able to add my User to the docker group and xhost + disables access control to the x server.

Its possible that the docker may not be playing nice as well so make sure to remove docker before installing fresh. Hopefully this gets you further. Note im using the docker engine directly on linux not docker desktop

**Comment by zlynch2** [comment]
Closing this per reply regarding 42 to work in the other issue #809
